INSERT INTO library_bdd.book (author,collection,description,editor,img_path_th_attribute,is_loan_available,is_online,is_reservation_available,isbn,nb_copy,release_date,short_description,stock,title) VALUES
	 ('author1','collection1','desc1 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer sed velit eget leo pharetra pretium. Duis imperdiet a turpis vitae mattis. Praesent molestie at turpis sit amet lacinia. Cras sed dui at massa ultricies fringilla quis sit amet lectus.</p><p>Donec quis ultrices risus. Phasellus lobortis nec dolor vel porttitor. Nam eu mauris tortor. Integer pretium vel dui et luctus. Integer sed odio vestibulum mi pellentesque aliquam. Donec lacinia cursus arcu sed lobortis. Mauris efficitur tellus in nulla posuere viverra.</p>','editor1','/img/book/book1_cover_400x400.jpg',1,1,1,'isbn1',3,'2018-08-19 16:22:09','desc1 Vi simulationem difficillimum aliis et placuerat placuerat simulat...',3,'titre1 Lorem ipsum'),
	 ('author2','collection2','desc2 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer sed velit eget leo pharetra pretium. Duis imperdiet a turpis vitae mattis. Praesent molestie at turpis sit amet lacinia. Cras sed dui at massa ultricies fringilla quis sit amet lectus.</p><p>Donec quis ultrices risus. Phasellus lobortis nec dolor vel porttitor. Nam eu mauris tortor. Integer pretium vel dui et luctus. Integer sed odio vestibulum mi pellentesque aliquam. Donec lacinia cursus arcu sed lobortis. Mauris efficitur tellus in nulla posuere viverra.</p>','editor2','/img/book/book2_cover_400x400.jpg',1,1,1,'isbn2',2,'2020-01-24 17:22:09','desc2 Vi simulationem difficillimum aliis et placuerat placuerat simulat...',1,'titre2 Lorem ipsum'),
	 ('author3','collection3','desc3 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer sed velit eget leo pharetra pretium. Duis imperdiet a turpis vitae mattis. Praesent molestie at turpis sit amet lacinia. Cras sed dui at massa ultricies fringilla quis sit amet lectus.</p><p>Donec quis ultrices risus. Phasellus lobortis nec dolor vel porttitor. Nam eu mauris tortor. Integer pretium vel dui et luctus. Integer sed odio vestibulum mi pellentesque aliquam. Donec lacinia cursus arcu sed lobortis. Mauris efficitur tellus in nulla posuere viverra.</p>','editor3','/img/book/book3_cover_400x400.jpg',1,1,1,'isbn3',1,'2020-05-22 16:22:09','desc3 Vi simulationem difficillimum aliis et placuerat placuerat simulat...',1,'titre3 Lorem ipsum'),
	 ('author4','collection4','desc4 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer sed velit eget leo pharetra pretium. Duis imperdiet a turpis vitae mattis. Praesent molestie at turpis sit amet lacinia. Cras sed dui at massa ultricies fringilla quis sit amet lectus.</p><p>Donec quis ultrices risus. Phasellus lobortis nec dolor vel porttitor. Nam eu mauris tortor. Integer pretium vel dui et luctus. Integer sed odio vestibulum mi pellentesque aliquam. Donec lacinia cursus arcu sed lobortis. Mauris efficitur tellus in nulla posuere viverra.</p>','editor4','/img/book/book4_cover_400x400.jpg',1,1,1,'isbn4',2,'2020-06-14 16:22:09','desc4 Vi simulationem difficillimum aliis et placuerat placuerat simulat...',2,'titre4 Lorem ipsum'),
	 ('author5','collection5','desc5 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer sed velit eget leo pharetra pretium. Duis imperdiet a turpis vitae mattis. Praesent molestie at turpis sit amet lacinia. Cras sed dui at massa ultricies fringilla quis sit amet lectus.</p><p>Donec quis ultrices risus. Phasellus lobortis nec dolor vel porttitor. Nam eu mauris tortor. Integer pretium vel dui et luctus. Integer sed odio vestibulum mi pellentesque aliquam. Donec lacinia cursus arcu sed lobortis. Mauris efficitur tellus in nulla posuere viverra.</p>','editor5','/img/book/book5_cover_400x400.jpg',1,1,1,'isbn5',5,'2019-05-01 16:22:09','desc5 Vi simulationem difficillimum aliis et placuerat placuerat simulat...',3,'titre5 Lorem ipsum'),
	 ('author6','collection6','desc6 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer sed velit eget leo pharetra pretium. Duis imperdiet a turpis vitae mattis. Praesent molestie at turpis sit amet lacinia. Cras sed dui at massa ultricies fringilla quis sit amet lectus.</p><p>Donec quis ultrices risus. Phasellus lobortis nec dolor vel porttitor. Nam eu mauris tortor. Integer pretium vel dui et luctus. Integer sed odio vestibulum mi pellentesque aliquam. Donec lacinia cursus arcu sed lobortis. Mauris efficitur tellus in nulla posuere viverra.</p>','editor6','/img/book/book6_cover_400x400.jpg',1,1,1,'isbn6',2,'2020-08-17 16:22:09','desc6 Vi simulationem difficillimum aliis et placuerat placuerat simulat...',2,'titre6 Lorem ipsum'),
	 ('author7','collection7','desc7 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer sed velit eget leo pharetra pretium. Duis imperdiet a turpis vitae mattis. Praesent molestie at turpis sit amet lacinia. Cras sed dui at massa ultricies fringilla quis sit amet lectus.</p><p>Donec quis ultrices risus. Phasellus lobortis nec dolor vel porttitor. Nam eu mauris tortor. Integer pretium vel dui et luctus. Integer sed odio vestibulum mi pellentesque aliquam. Donec lacinia cursus arcu sed lobortis. Mauris efficitur tellus in nulla posuere viverra.</p>','editor7','/img/book/book7_cover_400x400.jpg',1,1,1,'isbn7',3,'2019-02-02 17:22:09','desc7 Vi simulationem difficillimum aliis et placuerat placuerat simulat...',2,'titre7 Lorem ipsum'),
	 ('author8','collection8','desc8 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer sed velit eget leo pharetra pretium. Duis imperdiet a turpis vitae mattis. Praesent molestie at turpis sit amet lacinia. Cras sed dui at massa ultricies fringilla quis sit amet lectus.</p><p>Donec quis ultrices risus. Phasellus lobortis nec dolor vel porttitor. Nam eu mauris tortor. Integer pretium vel dui et luctus. Integer sed odio vestibulum mi pellentesque aliquam. Donec lacinia cursus arcu sed lobortis. Mauris efficitur tellus in nulla posuere viverra.</p>','editor8','/img/book/book8_cover_400x400.jpg',1,1,1,'isbn8',5,'2020-08-22 16:22:09','desc8 Vi simulationem difficillimum aliis et placuerat placuerat simulat...',5,'titre8 Lorem ipsum'),
	 ('author9','collection9','desc9 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer sed velit eget leo pharetra pretium. Duis imperdiet a turpis vitae mattis. Praesent molestie at turpis sit amet lacinia. Cras sed dui at massa ultricies fringilla quis sit amet lectus.</p><p>Donec quis ultrices risus. Phasellus lobortis nec dolor vel porttitor. Nam eu mauris tortor. Integer pretium vel dui et luctus. Integer sed odio vestibulum mi pellentesque aliquam. Donec lacinia cursus arcu sed lobortis. Mauris efficitur tellus in nulla posuere viverra.</p>','editor9','/img/book/book9_cover_400x400.jpg',1,1,1,'isbn9',5,'2019-10-14 16:22:09','desc9 Vi simulationem difficillimum aliis et placuerat placuerat simulat...',1,'titre9 Lorem ipsum'),
	 ('author10','collection10','desc10 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer sed velit eget leo pharetra pretium. Duis imperdiet a turpis vitae mattis. Praesent molestie at turpis sit amet lacinia. Cras sed dui at massa ultricies fringilla quis sit amet lectus.</p><p>Donec quis ultrices risus. Phasellus lobortis nec dolor vel porttitor. Nam eu mauris tortor. Integer pretium vel dui et luctus. Integer sed odio vestibulum mi pellentesque aliquam. Donec lacinia cursus arcu sed lobortis. Mauris efficitur tellus in nulla posuere viverra.</p>','editor10','/img/book/book10_cover_400x400.jpg',0,1,1,'isbn10',5,'2019-02-03 17:22:09','desc10 Vi simulationem difficillimum aliis et placuerat placuerat simula...',0,'titre10 Lorem ipsum');

INSERT INTO library_bdd.`user` (address,creation_date,email,first_name,last_name,password,reset_token,`role`) VALUES
	 (NULL,'2021-03-05 17:22:09','email@user1.fr','user1_firstName','user1_lastName','$2a$10$nvntrvYAzkQMc0uLSWvp/utBsb/wq5JP8m3OBTLoqDGIVyBtuafiO',NULL,'user'),
	 (NULL,'2021-03-05 17:22:09','email@user2.fr','user2_firstName','user2_lastName','$2a$10$54kjwYBh1l6d84DUT8PMz.xJrrGmyWS2x9VQaYrSPG3mTm/InnVna',NULL,'user'),
	 (NULL,'2021-03-05 17:22:09','email@user3.fr','user3_firstName','user3_lastName','$2a$10$tXPJhKkXZJyQQV/12qdB3uiu.isX66G.sSFZ.hRrQTjBlIOVSaote',NULL,'user'),
	 (NULL,'2021-03-05 17:22:09','email@user4.fr','user4_firstName','user4_lastName','$2a$10$zezD2X2p2no5p50NM2n5P.YCarpBBm1AOUYh23X.5O5w/MpkM/L6C',NULL,'user'),
	 (NULL,'2021-03-05 17:22:09','email@admin1.fr','admin1_firstName','admin1_lastName','$2a$10$asZVYOFP44NceOwgFCA5EeCoRyt8lQrYXXYMyUVxdRx9k8armr82G',NULL,'admin'),
	 (NULL,'2021-03-05 17:22:09','email@admin2.fr','admin2_firstName','admin2_lastName','$2a$10$e.n.7kTh08hHeNPSJokK/.LNgJpaRwst2AcwEgW3YYkXpWt6sdZLe',NULL,'admin');
	 

INSERT INTO library_bdd.book_loan (end_loan,is_loan_extended,loan_status,return_loan,start_loan,id_book,id_user) VALUES
	 ('2021-04-27 16:22:09',1,'Prolongé',NULL,'2021-03-02 17:22:09',1,1),
	 ('2021-03-31 16:22:09',0,'En cours',NULL,'2021-03-03 17:22:09',2,2),
	 ('2021-03-28 16:22:09',0,'En cours',NULL,'2021-02-28 17:22:09',2,1),
	 ('2021-04-01 16:22:09',0,'En cours',NULL,'2021-03-04 17:22:09',1,2),
	 ('2021-03-30 16:22:09',0,'En cours',NULL,'2021-03-02 17:22:09',3,3),
	 ('2021-03-31 16:22:09',0,'En cours',NULL,'2021-03-03 17:22:09',4,4),
	 ('2021-04-02 16:25:00',0,'En cours',NULL,'2021-03-05 17:25:00',10,1);
	 
INSERT INTO library_bdd.book_reservation (closing_date,creation_date,notification_date,reservation_status,id_book,id_user) VALUES
	 (NULL,'2021-03-03 17:22:10',NULL,'En cours',1,1),
	 (NULL,'2021-03-02 17:22:10',NULL,'En cours',2,2),
	 (NULL,'2021-03-01 17:22:10',NULL,'En cours',1,3),
	 (NULL,'2021-03-04 17:22:10',NULL,'En cours',2,4),
	 (NULL,'2021-03-01 17:22:11',NULL,'En cours',1,4),
	 (NULL,'2021-03-01 17:22:11',NULL,'En cours',3,1),
	 (NULL,'2021-03-05 17:25:21',NULL,'En cours',10,2),
	 ('2021-03-05 21:27:02','2021-03-05 17:26:30',NULL,'Terminé',10,3),
	 (NULL,'2021-03-05 21:25:35',NULL,'En cours',10,1);